name: lit-html
description: An efficient, expressive, extensible HTML templating library for JavaScript
markdown: kramdown
kramdown: 
  parse_block_html: true
google_analytics: UA-39334307-23
collections:
  guide:
    output: true
    permalink: /:collection/:title
include:
  - "_*_.html"
  - "_*_.*.html"
exclude: 
  - README.md
  - node_modules
